import { invoke } from "@tauri-apps/api/core";
import type { CalendarDay, CustomHoliday, DayData, ExportResult, HolidayUpdateResult, PeriodDigest, PeriodStats, SearchFilter, SearchPage, Settings, Task, Entry, NoteCard, Review, AiSummary, Attachment, Tag } from "../types";

const call = <T>(command: string, args?: Record<string, unknown>) => invoke<T>(command, args);

export const api = {
  getToday: () => call<DayData>("get_today"),
  getDay: (date: string) => call<DayData>("get_day", { date }),
  createTask: (date: string, title: string, carriedOver = false) => call<Task>("create_task", { date, title, carriedOver }),
  updateTask: (task: Task) => call<Task>("update_task", { task }),
  deleteTask: (id: number) => call<void>("delete_task", { id }),
  reorderTasks: (date: string, orderedIds: number[]) => call<Task[]>("reorder_tasks", { date, orderedIds }),
  createEntry: (date: string, body: string, icon: string) => call<Entry>("create_entry", { date, body, icon }),
  updateEntry: (entry: Entry, targetDate: string) => call<Entry>("update_entry", { entry, targetDate }),
  deleteEntry: (id: number) => call<void>("delete_entry", { id }),
  createNoteCard: (date: string) => call<NoteCard>("create_note_card", { date }),
  updateNoteCard: (card: NoteCard) => call<NoteCard>("update_note_card", { card }),
  deleteNoteCard: (id: number) => call<void>("delete_note_card", { id }),
  reorderNoteCards: (date: string, orderedIds: number[]) => call<NoteCard[]>("reorder_note_cards", { date, orderedIds }),
  importAttachmentFromPath: (path: string) => call<Attachment>("import_attachment_from_path", { path }),
  importAttachmentBytes: (name: string, mimeType: string, bytes: number[]) => call<Attachment>("import_attachment_bytes", { name, mimeType, bytes }),
  getAttachment: (id: string) => call<Attachment>("get_attachment", { id }),
  openAttachment: (id: string) => call<void>("open_attachment", { id }),
  saveReview: (date: string, review: Review) => call<void>("save_review", { date, review }),
  closeDay: (date: string) => call<void>("close_day", { date }),
  reopenDay: (date: string) => call<void>("reopen_day", { date }),
  calendar: (year: number, month: number) => call<CalendarDay[]>("get_calendar", { year, month }),
  setCustomHoliday: (date: string, name: string) => call<CustomHoliday>("set_custom_holiday", { date, name }),
  deleteCustomHoliday: (date: string) => call<void>("delete_custom_holiday", { date }),
  updateNationalHolidays: () => call<HolidayUpdateResult>("update_national_holidays"),
  search: (filter: SearchFilter) => call<SearchPage>("search_entries", { filter }),
  periodStats: (start: string, end: string, compareStart?: string, compareEnd?: string) => call<PeriodStats>("get_period_stats", { start, end, compareStart: compareStart ?? null, compareEnd: compareEnd ?? null }),
  periodDigest: (start: string, end: string) => call<PeriodDigest>("get_period_digest", { start, end }),
  onThisDay: (date: string, yearsBack = 3) => call<DayData[]>("get_on_this_day", { date, yearsBack }),
  listTags: () => call<Tag[]>("list_tags"),
  createTag: (name: string, color: string) => call<Tag>("create_tag", { name, color }),
  updateTag: (tag: Tag) => call<Tag>("update_tag", { tag }),
  deleteTag: (id: number) => call<void>("delete_tag", { id }),
  setTaskTags: (id: number, tagIds: number[]) => call<Tag[]>("set_task_tags", { id, tagIds }),
  setEntryTags: (id: number, tagIds: number[]) => call<Tag[]>("set_entry_tags", { id, tagIds }),
  setNoteCardTags: (id: number, tagIds: number[]) => call<Tag[]>("set_note_card_tags", { id, tagIds }),
  getSettings: () => call<Settings>("get_settings"),
  saveSettings: (settings: Settings) => call<void>("save_settings", { settings }),
  runAi: (date: string) => call<AiSummary>("run_daily_ai", { date }),
  cancelAi: () => call<void>("cancel_ai"),
  createBackup: () => call<string>("create_backup"),
  exportDayMarkdown: (date: string, path: string) => call<ExportResult>("export_day_markdown", { date, path }),
  exportPeriodMarkdown: (start: string, end: string, directory: string) => call<ExportResult[]>("export_period_markdown", { start, end, directory }),
  exportNoteMarkdown: (noteId: number, path: string) => call<ExportResult>("export_note_markdown", { noteId, path })
};
